services:
  app:
    image: epsilon/restaurant:app
    container_name: app
    restart: unless-stopped
    tty: true
    env_file: .env
    depends_on:
      - cache
    networks:
      - restaurant-prod

  web_server:
    image: epsilon/restaurant:web_server
    container_name: web_server
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - restaurant-prod

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "8889:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'epsilonrestaurant'
      MYSQL_DATABASE: 'restaurant'
      MYSQL_USER: 'dbmanager'
      MYSQL_PASSWORD: 'dbmanager'
    networks:
      - restaurant-prod

  cache:
    image: redis:alpine
    container_name: cache
    restart: unless-stopped
    networks:
      - restaurant-prod

volumes:
  dbdata:

networks:
  restaurant-prod:
    driver: bridge