name: CI/CD for Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker images
    - name: Build and push Laravel app image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant_epsilon:app_latest -f Docker/Dockerfile/app.Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/restaurant_epsilon:app_latest

    # Step 4: Set up Minikube
    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.13.0
      with:
        minikube version: 'v1.34.0'
        kubernetes version: 'v1.31.1'
        github token: ${{ secrets.GITHUB_TOKEN }}
        driver: docker

    # Step 5: Deploy to Minikube
    - name: Apply Kubernetes configuration
      run: |
        kubectl apply -f deployment.yaml
